---
name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      # Checkout the code
      - name: Checkout Conditions
        uses: actions/checkout@v3
      
      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      # AWS Credential Verification
      - name: Verify AWS CLI Configuration
        run: |
          aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # AWS Configure
      - name: Configure AWS Credntials
        run: |
          aws configure set aws-access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile temp
          aws configure set aws-secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile temp
          aws configure set region us-east-1 --profile temp
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Terraform Format check
      - name: Terraform Format Check
        run: terraform fmt -check

      # Terraform Validate
      - name: Terraform validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      # Terraform Apply
      - name: Terraform Apply
        # if: github.event_name == push
        run: terraform apply -auto-approve tfplan

      # Store Terraform State file
      - name: Upload Terraform State
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: terraform.tfstate


      
