---
name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      # Checkout the code
      - name: Checkout Conditions
        uses: actions/checkout@v3
      
      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Download Available terraform.tfstate file
      - name: Download terraform.tfstate file
        uses: actions/download-artifact@v4
        with:
          name: terraform.tfstate
          path: ./terraform.tfstate
        continue-on-error: true

      # Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Terraform Format check
      - name: Terraform Format Check
        run: terraform fmt -check

      # Terraform Validate
      - name: Terraform validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      # Terraform Apply
      - name: Terraform Apply
        # if: github.event_name == push
        run: terraform apply -auto-approve tfplan

      # Terraform State management
      - name: Save terraform.tfstate file
        uses: actions/upload-artifact@v3
        with:
          name: terraform.tfstate
          path: ./terraform.tfstate
      
