---
name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      # Checkout the code
      - name: Checkout Conditions
        uses: actions/checkout@v3
      
      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      # Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Terraform Format check
      - name: Terraform Format Check
        run: terraform fmt -check

      # Terraform Validate
      - name: Terraform validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      #Terraform Apply
      - name: Terraform Apply
        if: github.event_name == push
        run: terraform apply -auto-approve tfplan

      
