name: Test Local Runner

on:
  push:
    branches:
      - main
      - dev
      - qa
      - stg
  pull_request:
    branches:
      - dev
      - qa
      - stg
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print message
        run: echo "Hello from the local runner!"
      - name: Check AWS connection
        run : aws s3 ls --profile 100daysofdevops
